#!/usr/bin/env bash
if [ -f ".index" ]; then
    dir=$(fzf < .index | cut -f1 -d\ )
else
    dir=$(find . -maxdepth 1 -type d | fzf)
fi
if [ ! -z $dir ]; then
    if [ -d $dir ]; then
        cd $dir
        pwd
    fi
fi
